# Generated by Django 3.0.7 on 2020-06-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('creation_date', models.CharField(max_length=120)),
                ('update_date', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
            ],
        ),
    ]
