# Generated by Django 3.0.7 on 2020-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('CONSTRUCTION', 'CONSTRUCTION'), ('SPECIAL_EVENT', 'SPECIAL_EVENT'), ('INCIDENT', 'INCIDENT'), ('WEATHER_CONDITION', 'WEATHER_CONDITION'), ('ROAD_CONDITION', 'ROAD_CONDITION')], max_length=17),
        ),
        migrations.AlterField(
            model_name='report',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Por validar', 'Por validar'), ('Validade', 'Validado'), ('Resolvido', 'Resolvido')], default='Por validar', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
