# Generated by Django 3.0.7 on 2020-06-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200628_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Por validar', 'Por validar'), ('Validado', 'Validado'), ('Resolvido', 'Resolvido')], default='Por validar', max_length=20),
        ),
    ]
